version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_14
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db-user.sh:/docker-entrypoint-initdb.d/init-user-db.sh

volumes:
  postgres_data:
    driver: local
     
